export const GET_MOVIES = 'GET_MOVIES';
export const ERROR_MOVIES = 'ERROR_MOVIES';

export const GET_AMERICAN_MOVIES = 'GET_AMERICAN_MOVIES';
export const ERROR_AMERICAN_MOVIES = 'ERROR_AMERICAN_MOVIES';

export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const ERROR_POPULAR_MOVIES = 'ERROR_POPULAR_MOVIES';

export const GET_KID_MOVIES = 'GET_KID_MOVIES';
export const ERROR_KID_MOVIES = 'ERROR_KID_MOVIES';

export const GET_ANIME_MOVIES = 'GET_ANIME_MOVIES';
export const ERROR_ANIME_MOVIES = 'ERROR_ANIME_MOVIES';

export const GET_GENRES = 'GET_GENRES'
export const ERROR_GENRES = 'ERROR_GENRES'

